// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharpPowerTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "XSharpPowerTools.821a9ef3-feda-412d-b004-767f380c7336";
        public const string Name = "XSharpPowerTools";
        public const string Description = @"A set of tools for XSharp Developers";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Infominds Ag";
        public const string Tags = "";
    }
}
