// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharpPowerTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string XSharpPowerToolsString = "24100142-dc8c-4a86-a29b-99bbaf6bab3c";
        public static Guid XSharpPowerTools = new Guid(XSharpPowerToolsString);

        public const string UIContextGuidString = "10534154-102d-46e2-aba8-a6bfa25ba0be";
        public static Guid UIContextGuid = new Guid(UIContextGuidString);

        public const string CodeBrowserResultsToolWindowGuidString = "d3b3ebd9-87d1-41cd-bf84-268d88953417";
        public static Guid CodeBrowserResultsToolWindowGuid = new Guid(CodeBrowserResultsToolWindowGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MySubMenu = 0x0002;
        public const int MySubMenuGroup = 0x0003;
        public const int MyContextMenuGroup = 0x0004;
        public const int CodeBrowserCommand = 0x0100;
        public const int FindNamespaceCommand = 0x0110;
    }
}